-- BASE LIMPA: BravoPay + Supabase
-- Execute no SQL Editor. Não insere doações nem apoiadores fictícios.

begin;
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.payment_profiles (
  id uuid primary key default gen_random_uuid(),
  label text not null unique default 'principal',
  payer_name text not null,
  payer_email text not null,
  payer_document varchar(14) not null,
  payer_phone varchar(15),
  is_active boolean not null default true,
  usage_count bigint not null default 0,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_profiles_valid_document check (payer_document ~ '^[0-9]{11}$' or payer_document ~ '^[0-9]{14}$'),
  constraint payment_profiles_valid_phone check (payer_phone is null or payer_phone ~ '^[0-9]{10,15}$')
);

drop trigger if exists trg_payment_profiles_updated_at on public.payment_profiles;
create trigger trg_payment_profiles_updated_at before update on public.payment_profiles
for each row execute function public.set_updated_at();

create table if not exists public.donations (
  id uuid primary key default gen_random_uuid(),
  external_id text not null unique,
  transaction_id text unique,
  amount numeric(12,2) not null check (amount >= 5),
  fee numeric(12,2),
  status text not null default 'CREATING'
    check (status in ('CREATING','PENDING','COMPLETED','FAILED','REFUNDED','CHARGEBACK')),
  donor_name text,
  donor_email text,
  donor_document_last4 varchar(4),
  public_name text,
  show_public boolean not null default false,
  display_mode text not null default 'none' check (display_mode in ('supporter','popup','none')),
  qrcode_emv text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  platform varchar(32) not null default 'BRAVOPAY',
  gateway_payload jsonb not null default '{}'::jsonb,
  payment_profile_id uuid references public.payment_profiles(id),
  requester_hash text,
  generation_key text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_donations_updated_at on public.donations;
create trigger trg_donations_updated_at before update on public.donations
for each row execute function public.set_updated_at();

create unique index if not exists donations_generation_key_unique_idx on public.donations(generation_key) where generation_key is not null;
create index if not exists donations_status_created_idx on public.donations(status, created_at desc);
create index if not exists donations_requester_created_idx on public.donations(requester_hash, created_at desc) where requester_hash is not null;
create index if not exists donations_display_mode_paid_idx on public.donations(display_mode, paid_at desc) where status = 'COMPLETED';

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text not null,
  transaction_id text not null,
  external_id text,
  status text not null,
  payload jsonb not null,
  received_at timestamptz not null default now()
);

create table if not exists public.payment_generation_audit (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('CREATED','REUSED','BLOCKED','FAILED')),
  external_id text,
  amount numeric(12,2),
  payment_profile_id uuid references public.payment_profiles(id),
  requester_hash text not null,
  user_agent_hash text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_generation_audit_requester_idx on public.payment_generation_audit(requester_hash, created_at desc);

drop function if exists public.claim_payment_profile();

create function public.claim_payment_profile()
returns table (id uuid, payer_name text, payer_email text, payer_document text, payer_phone text)
language plpgsql security definer set search_path = public as $$
declare selected_id uuid;
begin
  select p.id into selected_id
  from public.payment_profiles p
  where p.is_active = true
  order by p.usage_count asc, p.last_used_at asc nulls first, p.created_at asc
  for update skip locked limit 1;

  if selected_id is null then return; end if;

  update public.payment_profiles
  set usage_count = usage_count + 1, last_used_at = now(), updated_at = now()
  where payment_profiles.id = selected_id;

  return query
  select p.id, p.payer_name, p.payer_email, p.payer_document::text, p.payer_phone::text
  from public.payment_profiles p where p.id = selected_id;
end;
$$;

alter table public.payment_profiles enable row level security;
alter table public.donations enable row level security;
alter table public.webhook_events enable row level security;
alter table public.payment_generation_audit enable row level security;

revoke all on table public.payment_profiles, public.donations, public.webhook_events, public.payment_generation_audit from public, anon, authenticated;
grant select, insert, update, delete on table public.payment_profiles, public.donations, public.webhook_events, public.payment_generation_audit to service_role;
revoke all on function public.claim_payment_profile() from public, anon, authenticated;
grant execute on function public.claim_payment_profile() to service_role;

create table if not exists public.supporter_like_totals (
  supporter_key text primary key,
  like_count smallint not null default 0,
  updated_at timestamptz not null default now(),
  constraint supporter_like_totals_key_length
    check (char_length(supporter_key) between 1 and 160),
  constraint supporter_like_totals_count_range
    check (like_count between 0 and 50)
);

create table if not exists public.supporter_like_votes (
  supporter_key text not null
    references public.supporter_like_totals(supporter_key)
    on delete cascade,
  voter_hash text not null,
  created_at timestamptz not null default now(),
  primary key (supporter_key, voter_hash),
  constraint supporter_like_votes_hash_length
    check (char_length(voter_hash) between 32 and 128)
);

create index if not exists supporter_like_votes_voter_idx
on public.supporter_like_votes (voter_hash);

drop function if exists public.set_supporter_like(text, text, boolean);

create function public.set_supporter_like(
  p_supporter_key text,
  p_voter_hash text,
  p_liked boolean
)
returns table (
  liked boolean,
  like_count integer,
  max_reached boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_count integer := 0;
  already_liked boolean := false;
begin
  p_supporter_key := trim(coalesce(p_supporter_key, ''));
  p_voter_hash := trim(coalesce(p_voter_hash, ''));

  if char_length(p_supporter_key) < 1 or char_length(p_supporter_key) > 160 then
    raise exception 'supporter_key inválida';
  end if;

  if char_length(p_voter_hash) < 32 or char_length(p_voter_hash) > 128 then
    raise exception 'voter_hash inválido';
  end if;

  insert into public.supporter_like_totals (
    supporter_key,
    like_count,
    updated_at
  )
  values (
    p_supporter_key,
    0,
    now()
  )
  on conflict (supporter_key) do nothing;

  select total.like_count
  into current_count
  from public.supporter_like_totals as total
  where total.supporter_key = p_supporter_key
  for update;

  select exists (
    select 1
    from public.supporter_like_votes as vote
    where vote.supporter_key = p_supporter_key
      and vote.voter_hash = p_voter_hash
  )
  into already_liked;

  if p_liked then
    if already_liked then
      return query
      select true, current_count, current_count >= 50;
      return;
    end if;

    if current_count >= 50 then
      return query
      select false, 50, true;
      return;
    end if;

    insert into public.supporter_like_votes (
      supporter_key,
      voter_hash
    )
    values (
      p_supporter_key,
      p_voter_hash
    );

    update public.supporter_like_totals as total
    set
      like_count = least(50, total.like_count + 1),
      updated_at = now()
    where total.supporter_key = p_supporter_key
    returning total.like_count
    into current_count;

    return query
    select true, current_count, current_count >= 50;
    return;
  end if;

  if already_liked then
    delete from public.supporter_like_votes as vote
    where vote.supporter_key = p_supporter_key
      and vote.voter_hash = p_voter_hash;

    update public.supporter_like_totals as total
    set
      like_count = greatest(0, total.like_count - 1),
      updated_at = now()
    where total.supporter_key = p_supporter_key
    returning total.like_count
    into current_count;
  end if;

  return query
  select false, current_count, current_count >= 50;
end;
$$;

alter table public.supporter_like_totals enable row level security;
alter table public.supporter_like_votes enable row level security;

revoke all on table public.supporter_like_totals from public, anon, authenticated;
revoke all on table public.supporter_like_votes from public, anon, authenticated;
revoke all on function public.set_supporter_like(text, text, boolean)
from public, anon, authenticated;

grant select, insert, update, delete
on table public.supporter_like_totals
to service_role;

grant select, insert, update, delete
on table public.supporter_like_votes
to service_role;

grant execute
on function public.set_supporter_like(text, text, boolean)
to service_role;

notify pgrst, 'reload schema';

commit;
notify pgrst, 'reload schema';

-- INSIRA/ATUALIZE O PERFIL REAL SEPARADAMENTE, sem máscara no CPF/CNPJ:
-- insert into public.payment_profiles(label,payer_name,payer_email,payer_document,payer_phone,is_active)
-- values ('principal','NOME REAL','email@exemplo.com','00000000000','11999999999',true)
-- on conflict(label) do update set
-- payer_name=excluded.payer_name,payer_email=excluded.payer_email,
-- payer_document=excluded.payer_document,payer_phone=excluded.payer_phone,
-- is_active=excluded.is_active,updated_at=now();
