import 'dotenv/config';import express from 'express';import cors from 'cors';import helmet from 'helmet';import QRCode from 'qrcode';import crypto from 'node:crypto';import {createPix} from './bravopay.js';import {insertDonation,updateDonation,getDonation,paidTotal} from './database.js';
const app=express(),origins=String(process.env.FRONTEND_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors({origin:(origin,cb)=>!origin||origins.includes(origin)?cb(null,true):cb(new Error('Origem não permitida'))}));
app.get('/health',(_,res)=>res.json({ok:true,service:'amor-salva'}));
app.post('/api/webhooks/bravopay',express.raw({type:'application/json'}),async(req,res)=>{try{const raw=req.body.toString('utf8'),sig=req.get('BravoPay-Signature')||req.get('X-Bravopay-Signature')||'';if(!verify(raw,sig,process.env.BRAVOPAY_WEBHOOK_SECRET))return res.status(401).json({error:'Assinatura inválida'});const evt=JSON.parse(raw),tx=evt.data||{};if(tx.external_reference)await updateDonation(tx.external_reference,{status:mapStatus(tx.status),provider_id:tx.id||null,paid_at:tx.paid_at||null,updated_at:new Date().toISOString()});res.json({received:true})}catch(e){console.error(e);res.status(400).json({error:'Webhook inválido'})}});
app.use(express.json({limit:'200kb'}));
app.post('/api/donations/create',async(req,res)=>{try{const amount=Number(req.body.amount);if(![10,30,50,100,200,300,500,700,1000].includes(amount))return res.status(422).json({error:'Valor de doação inválido.'});const name=String(req.body.name||'').trim().slice(0,100),externalId=`amor_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`;const tx=await createPix({amount,name,externalReference:externalId,tracking:req.body}),pixCode=tx?.pix?.copy_paste;if(!pixCode)throw new Error('A operadora não retornou o código PIX.');const qrImage=await QRCode.toDataURL(pixCode,{margin:1,width:640});await insertDonation({external_reference:externalId,provider_id:tx.id||null,amount,status:'PENDING',donor_name:name||null,show_public:Boolean(name)&&req.body.showPublic===true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});res.json({externalId,amount,qrImage,expiresAt:tx?.pix?.expires_at||null})}catch(e){console.error('create donation',e);res.status(502).json({error:e.message||'Não foi possível gerar o pagamento.'})}});
app.get('/api/donations/:id/status',async(req,res)=>{try{const d=await getDonation(req.params.id);if(!d)return res.status(404).json({error:'Doação não encontrada.'});res.json({status:d.status,amount:d.amount})}catch{res.status(500).json({error:'Falha ao consultar pagamento.'})}});
app.get('/api/campaign',async(_,res)=>{try{const goal=Number(process.env.CAMPAIGN_GOAL||130000),initial=Number(process.env.CAMPAIGN_INITIAL_AMOUNT||27847),raised=initial+await paidTotal();res.json({goal,raised,percentage:Number(((raised/goal)*100).toFixed(1))})}catch{res.json({goal:130000,raised:27847,percentage:21.4})}});
app.use((_,res)=>res.status(404).json({error:'Rota não encontrada.'}));
function mapStatus(s){return['PAID','COMPLETED'].includes(String(s).toUpperCase())?'COMPLETED':['FAILED','EXPIRED','REFUNDED','CHARGEBACK'].includes(String(s).toUpperCase())?'FAILED':'PENDING'}
function verify(raw,header,secret){try{if(!secret||!header)return false;const p=Object.fromEntries(header.split(',').map(x=>x.split('='))),t=Number(p.t);if(!t||Math.abs(Date.now()/1000-t)>300)return false;const expected=crypto.createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex');return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(p.v1||''))}catch{return false}}
app.listen(process.env.PORT||10000,()=>console.log(`Amor Salva backend ativo na porta ${process.env.PORT||10000}`));
