import './styles.css';
const API=String(import.meta.env.VITE_API_BASE_URL||'').trim().replace(/\/$/,'');
const VALUES=[10,30,50,100,200,300,500,700,1000];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const slides=[1,2,3,4,5,6,7,8,9,10].map(n=>`/assets/${n}.png`);
const supporters=[['AN','Ana M.','Há 2 min',50],['CR','Carlos R.','Há 12 min',100],['MP','Muralha P.','Há 20 min',50],['MS','Maria S.','Há 34 min',200]];
const app=document.querySelector('#app');
app.innerHTML=`
<header class="topbar"><div class="wrap nav"><a class="brand" href="#inicio"><img src="/assets/logo-amor-salva.png" alt="Amor Salva"></a><button class="share" id="shareBtn">Compartilhar</button></div></header>
<main id="inicio">
<section class="hero wrap"><img class="hero-img" src="/assets/4.png" alt="Maria Sônia e Ana Júlia"><span class="kicker">CAMPANHA AMOR SALVA</span><h1>O benefício foi cortado. Elas podem perder a casa.</h1><p>Maria Sônia dedica a vida aos cuidados da filha Ana Júlia, que vive com paralisia cerebral severa e precisa de atenção integral.</p><button class="primary" data-donate>Quero ajudar agora</button></section>
<section class="progress-card wrap"><div class="progress-head"><div><strong id="raised">R$ 27.847,00</strong><span>arrecadados</span></div><b id="percent">21,4%</b></div><div class="track"><span id="bar" style="width:21.4%"></span></div><div class="goal"><span>Meta: <b id="goal">R$ 130.000,00</b></span><span>Campanha ativa</span></div></section>
<section class="story wrap"><h2>Uma vida inteira dedicada ao cuidado</h2><p>A história de Maria Sônia e Ana Júlia é marcada por superação. Durante a gravidez, Maria Sônia teve dengue hemorrágica. Ana Júlia nasceu com hidrocefalia e paralisia cerebral severa e, desde então, necessita de cuidados constantes.</p><p>As despesas incluem fraldas especiais, medicamentos neurológicos, alimentação clínica e uma moradia segura e adaptada. A renda atual não cobre tudo o que elas precisam.</p><blockquote>“Choro escondida para não desanimar meus filhos. Se eu fraquejar, quem cuidará da Júlia? Ela é toda a minha vida.”</blockquote></section>
<section class="carousel wrap"><div class="slides">${slides.map((src,i)=>`<img src="${src}" alt="Registro da campanha ${i+1}" loading="lazy">`).join('')}</div></section>
<section class="impact"><div class="wrap"><h2>Como sua ajuda faz diferença</h2><div class="impact-grid"><article><strong>R$ 30</strong><p>Contribui para fraldas e itens de higiene.</p></article><article><strong>R$ 100</strong><p>Ajuda na compra de medicamentos e insumos.</p></article><article><strong>R$ 300</strong><p>Apoia alimentação clínica e despesas essenciais.</p></article><article><strong>R$ 500</strong><p>Contribui para uma moradia mais segura e adaptada.</p></article></div></div></section>
<section class="costs wrap"><h2>Necessidades contínuas</h2><div class="cost-card"><img src="/assets/hidantal.jpg" alt="Medicamento"><div><b>Medicamentos neurológicos</b><span>Uso contínuo conforme acompanhamento médico.</span></div></div><div class="cost-card"><img src="/assets/7.png" alt="Cuidados diários"><div><b>Cuidados diários</b><span>Fraldas, alimentação, higiene e suporte integral.</span></div></div><div class="cost-card"><img src="/assets/8.png" alt="Moradia"><div><b>Moradia segura</b><span>Apoio para preservar um lar adequado às necessidades da família.</span></div></div></section>
<section class="supporters wrap"><h2>Últimas contribuições</h2><div class="support-list">${supporters.map(s=>`<article><span class="avatar">${s[0]}</span><div><b>${s[1]}</b><small>${s[2]}</small></div><strong>${money.format(s[3])}</strong></article>`).join('')}</div></section>
<section class="faq wrap"><h2>Transparência e respostas</h2><details open><summary>Como os recursos serão usados?</summary><p>Na moradia, alimentação, fraldas, medicamentos, insumos e necessidades diretamente relacionadas aos cuidados de Ana Júlia.</p></details><details><summary>Posso doar de forma anônima?</summary><p>Sim. O nome é opcional e o pagamento pode ser gerado sem identificação pública.</p></details><details><summary>Como o pagamento é confirmado?</summary><p>O sistema acompanha a cobrança e confirma a doação quando o gateway informa o pagamento.</p></details></section>
<section class="about wrap"><img src="/assets/logo-amor-salva.png" alt="Amor Salva"><h2>Sobre o Amor Salva</h2><p>Uma iniciativa solidária dedicada a conectar pessoas dispostas a ajudar famílias em situação de vulnerabilidade.</p></section>
</main>
<button class="sticky-donate" data-donate>Doar agora</button>
<div class="modal" id="modal" aria-hidden="true"><div class="backdrop" data-close></div><section class="sheet" role="dialog" aria-modal="true"><button class="close" data-close>×</button><div id="valueStep" class="step active"><span class="kicker">AJUDE COM O VALOR QUE PUDER</span><h2>Escolha sua contribuição</h2><div class="value-grid">${VALUES.map(v=>`<button data-value="${v}">${money.format(v).replace(',00','')}</button>`).join('')}</div><p class="secure">Pagamento por PIX gerado com segurança.</p></div><form id="donorForm" class="step"><button class="back" type="button" id="backValues">← Alterar valor</button><p class="selected">Doação de <b id="selectedValue"></b></p><label>Seu nome <span>(opcional)</span><input name="name" maxlength="100" placeholder="Deixe vazio para doar anonimamente"></label><label class="check"><input type="checkbox" name="showPublic"> Mostrar meu nome entre os apoiadores</label><button class="primary" id="generate" type="submit">Gerar QR Code PIX</button><p class="error" id="error"></p></form><div id="pixStep" class="step pix"><h2>Escaneie para doar</h2><p>Valor: <b id="pixAmount"></b></p><div class="qr"><img id="qrImage" alt="QR Code PIX"></div><p class="waiting"><span></span>Aguardando confirmação do pagamento…</p><button class="secondary" data-close>Fechar</button></div><div id="successStep" class="step success"><div>✓</div><h2>Doação confirmada</h2><p>Obrigado por fazer parte desta corrente de amor.</p><button class="primary" data-close>Concluir</button></div></section></div>`;
let selectedAmount=null,poll=null;const modal=document.querySelector('#modal');const steps=[...document.querySelectorAll('.step')];
const showStep=id=>steps.forEach(s=>s.classList.toggle('active',s.id===id));
const open=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('lock');showStep('valueStep')};
const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('lock');clearInterval(poll)};
document.querySelectorAll('[data-donate]').forEach(b=>b.addEventListener('click',open));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',close));
document.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('click',()=>{selectedAmount=Number(b.dataset.value);document.querySelector('#selectedValue').textContent=money.format(selectedAmount);showStep('donorForm')}));
document.querySelector('#backValues').addEventListener('click',()=>showStep('valueStep'));
document.querySelector('#shareBtn').addEventListener('click',async()=>{const d={title:document.title,text:'Conheça esta campanha do Amor Salva',url:location.href};try{navigator.share?await navigator.share(d):await navigator.clipboard.writeText(location.href)}catch{}});
document.querySelector('#donorForm').addEventListener('submit',async e=>{e.preventDefault();const error=document.querySelector('#error');error.textContent='';const btn=document.querySelector('#generate');btn.disabled=true;btn.textContent='Gerando…';const fd=new FormData(e.currentTarget);const name=String(fd.get('name')||'').trim();const payload={amount:selectedAmount,name,showPublic:Boolean(name)&&fd.get('showPublic')==='on',...tracking()};try{const r=await fetch(`${API}/api/donations/create`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível gerar o PIX.');document.querySelector('#qrImage').src=data.qrImage;document.querySelector('#pixAmount').textContent=money.format(data.amount);showStep('pixStep');startPolling(data.externalId)}catch(err){error.textContent=err.message}finally{btn.disabled=false;btn.textContent='Gerar QR Code PIX'}});
function tracking(){const p=new URLSearchParams(location.search),o={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term','fbclid','gclid','ttclid'].forEach(k=>{const v=p.get(k);if(v)o[k]=v});return o}
function startPolling(id){clearInterval(poll);const check=async()=>{try{const r=await fetch(`${API}/api/donations/${encodeURIComponent(id)}/status`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.status==='COMPLETED'){clearInterval(poll);showStep('successStep');loadCampaign()}}catch{}};check();poll=setInterval(check,5000)}
async function loadCampaign(){if(!API)return;try{const r=await fetch(`${API}/api/campaign`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();document.querySelector('#raised').textContent=money.format(d.raised);document.querySelector('#goal').textContent=money.format(d.goal);document.querySelector('#percent').textContent=`${d.percentage}%`;document.querySelector('#bar').style.width=`${Math.min(100,d.percentage)}%`}catch{}}
loadCampaign();
